kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-nodes
data:
  prometheus.yml: |
    global: 
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting: 
      alertmanagers:
      - static_configs: 
        - targets: 
    rule_files:
    scrape_configs:
      - job_name: 'node'
        static_configs:
        - targets : ['192.168.43.55:9100']
      - job_name: 'docker'
        static_configs:
        - targets : ['192.168.43.77:1234']
