apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    env: deploy
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30004
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      env: deploy
  template:
    metadata:
      name: grafana-pod
      labels:
        env: deploy
    spec:
      containers:
        - name: g1
          image: devmohitlive/grafana
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-pvc
